### ISSUE TITLE
What is the ESP 32 Version number

### ISSUE THREAD

**Issue by pranaysharma** [OLIMEX/ESP32-POE-ISO#1]
Hi We want to use [secureboot v2](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html) feature in ESP32-POE-ISO-IND but we are not sure if the ESP32 inside is ESP32 Revision 3 or not. 
Could someone help?

**Comment by DanKoloff** [comment]
Do you already own ESP32-POE-ISO-IND or are you currently looking forward to buy one?

**Comment by pranaysharma** [comment]
Yes I own ESP32-POE-ISO-IND

**Comment by DanKoloff** [comment]
There is a hello world example in ESP-IDF for ESP32 that prints it, check here:

https://github.com/espressif/esp-idf/blob/master/examples/get-started/hello_world/main/hello_world_main.c
