### ISSUE TITLE
3D Integrated Models

### ISSUE THREAD

**Issue by markattecusa** [OLIMEX/ESP32-POE-ISO#10]
@DanKoloff 

Is it possible for 3d integrated models to be published with PCB changes? Last posting seems to be G1. 

https://github.com/OLIMEX/ESP32-POE-ISO/blob/master/HARDWARE/ESP32-PoE-ISO-Rev.G1/ESP32-PoE-ISO_Rev_G1.step

I can produce it if helpful, but someone may already have it.

Thanks!

**Comment by DanKoloff** [comment]
Sorry I don't understand the request. Can you explain it with more words and examples?

**Comment by DanKoloff** [comment]
If you request for STEP file you can export STEP via KiCAD - you can export STEP file via KiCAD (and KiCAD is free and open-source). Last time customers reported that the export works fine without any extra steps to take. Check my exchange with a customer:

https://github.com/OLIMEX/ESP32-POE-ISO/issues/6
