### ISSUE TITLE
3x4 Keypad problem

### ISSUE THREAD

**Issue by enschy** [OLIMEX/ESP32-POE-ISO#2]
I have problems to get an 4x4 Keypad working. Like this Example:
https://diyi0t.com/keypad-arduino-esp8266-esp32/
With the NodeMCU board works this, but with the ESP32 POE not. I have tested many GPIO combinations.

byte rowPins[ROWS] = {4, 3, 2, 1}; 
byte colPins[COLS] = {13, 14, 15, 16};

Whats wrong?
Thanks

**Comment by DanKoloff** [comment]
So it is working with ESP8266 board but not with ESP32 board? Maybe the code library is not compatible or requires something extra.
