### ISSUE TITLE
PHY nrst not mapped on any gpio

### ISSUE THREAD

**Issue by CyrilNeoFarm** [OLIMEX/ESP32-POE-ISO#5]
I am trying to use [micro-ROS as an esp-idf component.](https://github.com/micro-ROS/micro_ros_espidf_component) In order to use ethernet transport I need to write the PHY reset gpio number inside the menuconfig. However the nrst isn't mapped in the ESP32-POE-ISO. 
I tried to use the PHY_PWR gpio instead with no success.
Would you know any way to solve this issue ?

**Comment by DanKoloff** [comment]
Your inability to adapt custom component that you found online to work with our board, is not an issue with ESP32-POE-ISO. This is not the proper place to request software assistance. 

Maybe try joining the forums or contacting the the micro-ROS team.

Also LAN8710's NRST is pulled high via resistor. You can find NRST if you download the schematic and open it and use find, the schematic has the labels searchable.
